const KEY='usd_rmb_records_v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let records=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
function save(){localStorage.setItem(KEY,JSON.stringify(records))}
function money(n,p='$'){return p+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function num(n,d=2){return Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})}
function today(){return new Date().toISOString().slice(0,10)}
function monthNow(){return new Date().toISOString().slice(0,7)}
function go(id){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');$('#backBtn').classList.toggle('hidden',id==='home');const map={home:['汇率记录','本机保存 · 可导出 WPS'],input:['输入记录','日期、美金、汇率手动输入'],saved:['保存成功','可继续添加或返回首页'],all:['查看全部','所有记录与总计'],month:['按月查看','选择月份查看记录'],year:['年度汇总','选择年份查看记录'],backup:['导出/备份','Excel 给 WPS，JSON 用于恢复']};$('#pageTitle').textContent=map[id][0];$('#pageDesc').textContent=map[id][1];renderAll()}
function calcSummary(arr){const usd=arr.reduce((s,r)=>s+r.usd,0),cny=arr.reduce((s,r)=>s+r.cny,0);const avg=usd?cny/usd:0;return{count:arr.length,usd,cny,avg}}
function summaryHtml(s){if(!s.count)return '<div class="empty" style="grid-column:1/-1">暂无数据</div>';return `<div class="summary-item"><span>记录行数</span><strong>${s.count}</strong></div><div class="summary-item"><span>美金总金额</span><strong>${money(s.usd)}</strong></div><div class="summary-item"><span>平均汇率</span><strong>${num(s.avg,4)}</strong></div><div class="summary-item"><span>人民币总金额</span><strong>${money(s.cny,'¥')}</strong></div>`}
function listHtml(arr){if(!arr.length)return '<div class="empty">暂无数据</div>';return arr.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<div class="row"><div class="row-top"><span>${r.date}</span><span>汇率 ${num(r.rate,4)}</span></div><div class="row-main"><strong>${money(r.usd)}</strong><span>${money(r.cny,'¥')}</span></div>${r.note?`<div class="row-note">${escapeHtml(r.note)}</div>`:''}<button type="button" onclick="delRec('${r.id}')">删除</button></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function renderYears(){const years=[...new Set(records.map(r=>r.date.slice(0,4)))].sort((a,b)=>b.localeCompare(a));if(!years.length)years.push(new Date().getFullYear().toString());$('#yearSelect').innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('')}
function renderAll(){records=load();$('#homeSummary').innerHTML=summaryHtml(calcSummary(records));$('#allSummary').innerHTML=summaryHtml(calcSummary(records));$('#allList').innerHTML=listHtml(records);renderYears();const m=$('#monthInput').value||monthNow();$('#monthInput').value=m;const marr=records.filter(r=>r.date.slice(0,7)===m);$('#monthSummary').innerHTML=summaryHtml(calcSummary(marr));$('#monthList').innerHTML=listHtml(marr);const y=$('#yearSelect').value||new Date().getFullYear().toString();$('#yearSelect').value=y;const yarr=records.filter(r=>r.date.slice(0,4)===y);$('#yearSummary').innerHTML=summaryHtml(calcSummary(yarr));$('#yearList').innerHTML=listHtml(yarr)}
function updatePreview(){const usd=parseFloat($('#usdInput').value)||0,rate=parseFloat($('#rateInput').value)||0;$('#cnyPreview').textContent=money(usd*rate,'¥')}
function delRec(id){if(confirm('确定删除这条记录吗？')){records=records.filter(r=>r.id!==id);save();renderAll()}}
window.delRec=delRec;
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#backBtn').addEventListener('click',()=>go('home'));$('#dateInput').value=today();$('#monthInput').value=monthNow();$('#usdInput').addEventListener('input',updatePreview);$('#rateInput').addEventListener('input',updatePreview);$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const usd=parseFloat($('#usdInput').value),rate=parseFloat($('#rateInput').value);if(!usd||!rate)return alert('请填写美金金额和汇率');records.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2),date:$('#dateInput').value||today(),usd,rate,cny:usd*rate,note:$('#noteInput').value.trim()});save();$('#entryForm').reset();$('#dateInput').value=today();updatePreview();go('saved')});$('#monthInput').addEventListener('change',renderAll);$('#yearSelect').addEventListener('change',renderAll);
$('#exportJson').addEventListener('click',()=>downloadBlob(JSON.stringify(records,null,2),'汇率记录备份.json','application/json'));
$('#importJson').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data))throw new Error();records=data;save();alert('导入成功');go('home')}catch{alert('导入失败，请确认是本工具导出的 JSON')}});
$('#clearData').addEventListener('click',()=>{if(confirm('确定清空全部数据吗？此操作不能恢复。')){records=[];save();renderAll();alert('已清空')}});
$('#exportXlsx').addEventListener('click',()=>{if(!window.XLSX)return alert('Excel 导出组件加载失败，请联网后再试');const all=records.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({日期:r.date,美金金额:r.usd,汇率:r.rate,人民币金额:r.cny,备注:r.note||''}));const months=[...new Set(records.map(r=>r.date.slice(0,7)))].sort().map(m=>{const s=calcSummary(records.filter(r=>r.date.slice(0,7)===m));return{月份:m,记录行数:s.count,美金总金额:s.usd,平均汇率:s.avg,人民币总金额:s.cny}});const years=[...new Set(records.map(r=>r.date.slice(0,4)))].sort().map(y=>{const s=calcSummary(records.filter(r=>r.date.slice(0,4)===y));return{年份:y,记录行数:s.count,美金总金额:s.usd,平均汇率:s.avg,人民币总金额:s.cny}});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(all),'全部记录');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(months),'月度汇总');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(years),'年度汇总');XLSX.writeFile(wb,'美元人民币记录.xlsx')});
function downloadBlob(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});renderAll();
